## Helper functions for collecting Bayes R2 values across models.
## Source this file from the model scripts, then call record_bayes_R2()
## after each fitted model.

bayes_R2_csv_file <- file.path("tables", "bayes_R2_table.csv")
bayes_R2_tex_file <- file.path("tables", "bayes_R2_table.tex")

empty_bayes_R2_table <- function(){
  data.frame(
    ModelID = character(),
    ModelSet = character(),
    Host = character(),
    Parasite = character(),
    Estimate = numeric(),
    Est.Error = numeric(),
    Q2.5 = numeric(),
    Q97.5 = numeric(),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}

init_bayes_R2_table <- function(table_file = bayes_R2_csv_file,
                                reset = FALSE){
  if (!reset && file.exists(table_file)) {
    out <- read.csv(table_file, stringsAsFactors = FALSE,
                    check.names = FALSE)

    ## Keep only the expected columns, in the expected order.
    expected_cols <- names(empty_bayes_R2_table())
    missing_cols <- setdiff(expected_cols, names(out))
    if (length(missing_cols) > 0) {
      for (cc in missing_cols) out[[cc]] <- NA
    }
    out <- out[, expected_cols]
    return(out)
  }

  empty_bayes_R2_table()
}

parse_bayes_R2_model_id <- function(model_id){
  pieces <- strsplit(model_id, "_", fixed = TRUE)[[1]]

  if (pieces[1] == "network") {
    model_set <- "Genus-level network metrics"
    host <- pieces[2]
    parasite <- paste(pieces[-c(1, 2)], collapse = "_")
  } else {
    model_set <- "Species-level network metrics"
    host <- pieces[1]
    parasite <- paste(pieces[-1], collapse = "_")
  }

  host <- paste0(toupper(substr(host, 1, 1)), substr(host, 2, nchar(host)))

  parasite <- gsub("Presence", "", parasite)
  parasite <- gsub("Spp", " spp.", parasite)
  parasite <- gsub("_", " ", parasite)
  parasite <- trimws(parasite)

  list(
    ModelSet = model_set,
    Host = host,
    Parasite = parasite
  )
}

latex_escape <- function(x){
  x <- as.character(x)
  x <- gsub("&", "\\&", x, fixed = TRUE)
  x <- gsub("%", "\\%", x, fixed = TRUE)
  x <- gsub("_", "\\_", x, fixed = TRUE)
  x <- gsub("#", "\\#", x, fixed = TRUE)
  x <- gsub("$", "\\$", x, fixed = TRUE)
  x
}

format_bayes_R2_table <- function(r2_table, digits = 3){
  if (nrow(r2_table) == 0) {
    return(r2_table)
  }

  r2_table <- r2_table[order(r2_table$Host,
                             r2_table$Parasite,
                             r2_table$ModelSet), ]

  r2_table$Estimate <- round(r2_table$Estimate, digits)
  r2_table$Est.Error <- round(r2_table$Est.Error, digits)
  r2_table$Q2.5 <- round(r2_table$Q2.5, digits)
  r2_table$Q97.5 <- round(r2_table$Q97.5, digits)

  r2_table
}

write_bayes_R2_latex <- function(r2_table,
                                 tex_file = bayes_R2_tex_file,
                                 digits = 3,
                                 caption = "Bayesian R-squared estimates for host-parasite network models.",
                                 label = "tab:bayes-r2"){

  dir.create(dirname(tex_file), recursive = TRUE, showWarnings = FALSE)
  r2_table <- format_bayes_R2_table(r2_table, digits = digits)

  if (nrow(r2_table) == 0) {
    writeLines("% No Bayes R2 rows have been recorded yet.", tex_file)
    return(invisible(tex_file))
  }

  rows <- apply(r2_table, 1, function(rr){
    paste(
      latex_escape(rr[["ModelSet"]]),
      latex_escape(rr[["Host"]]),
      latex_escape(rr[["Parasite"]]),
      sprintf(paste0("%.", digits, "f"), as.numeric(rr[["Estimate"]])),
      sprintf(paste0("%.", digits, "f"), as.numeric(rr[["Est.Error"]])),
      sprintf(paste0("%.", digits, "f"), as.numeric(rr[["Q2.5"]])),
      sprintf(paste0("%.", digits, "f"), as.numeric(rr[["Q97.5"]])),
      sep = " & "
    )
  })

  rows <- paste0(rows, " \\\\")

  latex_lines <- c(
    "% Generated by src/makeBayesR2Table.R",
    "\\begin{table}[!ht]",
    "\\centering",
    paste0("\\caption{", latex_escape(caption), "}"),
    paste0("\\label{", latex_escape(label), "}"),
    "\\begin{tabular}{lllrrrr}",
    "\\hline",
    "Model set & Host & Parasite & Estimate & Est. error & Q2.5 & Q97.5 \\\\",
    "\\hline",
    rows,
    "\\hline",
    "\\end{tabular}",
    "\\end{table}"
  )

  writeLines(latex_lines, tex_file)
  invisible(tex_file)
}

write_bayes_R2_outputs <- function(r2_table,
                                   csv_file = bayes_R2_csv_file,
                                   tex_file = bayes_R2_tex_file,
                                   digits = 3){
  dir.create(dirname(csv_file), recursive = TRUE, showWarnings = FALSE)
  write.csv(format_bayes_R2_table(r2_table, digits = digits),
            file = csv_file,
            row.names = FALSE)
  write_bayes_R2_latex(r2_table, tex_file = tex_file, digits = digits)
  invisible(r2_table)
}

record_bayes_R2 <- function(r2_table,
                            model,
                            model_id,
                            csv_file = bayes_R2_csv_file,
                            tex_file = bayes_R2_tex_file,
                            digits = 3,
                            print_result = TRUE){

  r2 <- brms::bayes_R2(model)

  if (print_result) {
    print(r2)
  }

  r2_df <- as.data.frame(r2, check.names = FALSE)

  if ("R2" %in% rownames(r2_df)) {
    r2_df <- r2_df["R2", , drop = FALSE]
  } else {
    r2_df <- r2_df[1, , drop = FALSE]
  }

  meta <- parse_bayes_R2_model_id(model_id)

  new_row <- data.frame(
    ModelID = model_id,
    ModelSet = meta$ModelSet,
    Host = meta$Host,
    Parasite = meta$Parasite,
    Estimate = as.numeric(r2_df[["Estimate"]]),
    Est.Error = as.numeric(r2_df[["Est.Error"]]),
    Q2.5 = as.numeric(r2_df[["Q2.5"]]),
    Q97.5 = as.numeric(r2_df[["Q97.5"]]),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )

  ## Replace any previous row for this model so reruns do not duplicate rows.
  r2_table <- r2_table[r2_table$ModelID != model_id, , drop = FALSE]
  r2_table <- rbind(r2_table, new_row)

  write_bayes_R2_outputs(r2_table,
                         csv_file = csv_file,
                         tex_file = tex_file,
                         digits = digits)

  invisible(r2_table)
}
