## Helper functions for model diagnostics, posterior predictive checks,
## and supplement-ready project-inclusion tables.
##
## Source after src/makeBayesR2Table.R because this file reuses
## parse_bayes_R2_model_id() and latex_escape().

pp_check_dir <- file.path("figures", "pp_checks")
check_model_dir <- file.path("figures", "model_checks")
model_project_csv_file <- file.path("tables", "model_project_inclusion.csv")
model_project_tex_file <- file.path("tables", "model_project_inclusion.tex")

make_dir <- function(path){
  dir.create(path, recursive = TRUE, showWarnings = FALSE)
  invisible(path)
}

safe_one_line <- function(x){
  if (length(x) == 0 || all(is.na(x))) return("None")
  x <- sort(unique(as.character(x[!is.na(x)])))
  if (length(x) == 0) return("None")
  paste(x, collapse = "; ")
}

empty_model_project_table <- function(){
  data.frame(
    ModelID = character(),
    ModelSet = character(),
    Host = character(),
    Parasite = character(),
    IncludedProjects = character(),
    ExcludedProjects = character(),
    NRows = integer(),
    NSites = integer(),
    NYears = integer(),
    NScreened = numeric(),
    NPositive = numeric(),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}

init_model_project_table <- function(table_file = model_project_csv_file,
                                     reset = FALSE){
  if (!reset && file.exists(table_file)) {
    out <- read.csv(table_file, stringsAsFactors = FALSE,
                    check.names = FALSE)
    expected_cols <- names(empty_model_project_table())
    missing_cols <- setdiff(expected_cols, names(out))
    if (length(missing_cols) > 0) {
      for (cc in missing_cols) out[[cc]] <- NA
    }
    out <- out[, expected_cols]
    return(out)
  }

  empty_model_project_table()
}

write_model_project_latex <- function(project_table,
                                      tex_file = model_project_tex_file,
                                      caption = "Projects included in each host-parasite network model.",
                                      label = "tab:model-project-inclusion"){
  make_dir(dirname(tex_file))

  if (nrow(project_table) == 0) {
    writeLines("% No project-inclusion rows have been recorded yet.", tex_file)
    return(invisible(tex_file))
  }

  project_table <- project_table[order(project_table$Host,
                                       project_table$Parasite,
                                       project_table$ModelSet), ]

  rows <- apply(project_table, 1, function(rr){
    paste(
      latex_escape(rr[["ModelSet"]]),
      latex_escape(rr[["Host"]]),
      latex_escape(rr[["Parasite"]]),
      latex_escape(rr[["IncludedProjects"]]),
      latex_escape(rr[["ExcludedProjects"]]),
      rr[["NRows"]],
      rr[["NSites"]],
      rr[["NYears"]],
      rr[["NScreened"]],
      rr[["NPositive"]],
      sep = " & "
    )
  })

  rows <- paste0(rows, " \\\\")

  latex_lines <- c(
    "% Generated by src/makeModelOutputTables.R",
    "\\begin{table}[!ht]",
    "\\centering",
    "\\small",
    paste0("\\caption{", latex_escape(caption), "}"),
    paste0("\\label{", latex_escape(label), "}"),
    "\\begin{tabular}{lll p{3.4cm} p{3.4cm} rrrrr}",
    "\\hline",
    "Model set & Host & Parasite & Included projects & Excluded projects & Rows & Sites & Years & Screened & Positive \\\\",
    "\\hline",
    rows,
    "\\hline",
    "\\end{tabular}",
    "\\end{table}"
  )

  writeLines(latex_lines, tex_file)
  invisible(tex_file)
}

write_model_project_outputs <- function(project_table,
                                        csv_file = model_project_csv_file,
                                        tex_file = model_project_tex_file){
  make_dir(dirname(csv_file))
  project_table <- project_table[order(project_table$Host,
                                       project_table$Parasite,
                                       project_table$ModelSet), ]
  write.csv(project_table, file = csv_file, row.names = FALSE)
  write_model_project_latex(project_table, tex_file = tex_file)
  invisible(project_table)
}

record_model_projects <- function(project_table,
                                  model_id,
                                  data,
                                  response_col,
                                  trials_col,
                                  project_col = "ProjectSubProject",
                                  site_col = "Site",
                                  year_col = "Year",
                                  all_projects = NULL,
                                  csv_file = model_project_csv_file,
                                  tex_file = model_project_tex_file){
  meta <- parse_bayes_R2_model_id(model_id)

  included_projects <- if (project_col %in% names(data)) {
    sort(unique(as.character(data[[project_col]])))
  } else {
    character(0)
  }

  excluded_projects <- if (!is.null(all_projects)) {
    setdiff(sort(unique(as.character(all_projects))), included_projects)
  } else {
    character(0)
  }

  n_sites <- if (site_col %in% names(data)) {
    length(unique(data[[site_col]][!is.na(data[[site_col]])]))
  } else {
    NA_integer_
  }

  n_years <- if (year_col %in% names(data)) {
    length(unique(data[[year_col]][!is.na(data[[year_col]])]))
  } else {
    NA_integer_
  }

  n_screened <- if (trials_col %in% names(data)) {
    sum(data[[trials_col]], na.rm = TRUE)
  } else {
    NA_real_
  }

  n_positive <- if (response_col %in% names(data)) {
    sum(data[[response_col]], na.rm = TRUE)
  } else {
    NA_real_
  }

  new_row <- data.frame(
    ModelID = model_id,
    ModelSet = meta$ModelSet,
    Host = meta$Host,
    Parasite = meta$Parasite,
    IncludedProjects = safe_one_line(included_projects),
    ExcludedProjects = safe_one_line(excluded_projects),
    NRows = nrow(data),
    NSites = n_sites,
    NYears = n_years,
    NScreened = n_screened,
    NPositive = n_positive,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )

  ## Replace any previous row for this model so reruns do not duplicate rows.
  project_table <- project_table[project_table$ModelID != model_id, , drop = FALSE]
  project_table <- rbind(project_table, new_row)

  write_model_project_outputs(project_table,
                              csv_file = csv_file,
                              tex_file = tex_file)

  invisible(project_table)
}

save_pp_check_pdf <- function(model,
                              model_id,
                              resp = NULL,
                              ndraws = 1000,
                              width = 7,
                              height = 5,
                              out_dir = pp_check_dir){
  make_dir(out_dir)
  out_file <- file.path(out_dir, paste0(model_id, ".pdf"))

  tryCatch({
    p <- if (is.null(resp)) {
      brms::pp_check(model, ndraws = ndraws)
    } else {
      brms::pp_check(model, resp = resp, ndraws = ndraws)
    }

    grDevices::pdf(out_file, width = width, height = height)
    print(p)
    grDevices::dev.off()
  }, error = function(e){
    if (grDevices::dev.cur() > 1) grDevices::dev.off()
    warning(sprintf("pp_check failed for %s: %s", model_id, conditionMessage(e)))
  })

  invisible(out_file)
}

save_check_model_pdf <- function(model,
                                 model_id,
                                 width = 11,
                                 height = 8.5,
                                 out_dir = check_model_dir){
  make_dir(out_dir)
  out_file <- file.path(out_dir, paste0(model_id, ".pdf"))
  log_file <- file.path(out_dir, paste0(model_id, "_check_model_log.txt"))

  tryCatch({
    chk <- performance::check_model(model)

    grDevices::pdf(out_file, width = width, height = height)
    print(chk)
    grDevices::dev.off()

    writeLines(c("check_model completed successfully.",
                 paste("Output:", out_file)), log_file)
  }, error = function(e){
    if (grDevices::dev.cur() > 1) grDevices::dev.off()
    msg <- sprintf("check_model failed for %s: %s", model_id, conditionMessage(e))
    warning(msg)
    writeLines(msg, log_file)
  })

  invisible(out_file)
}

save_model_summary_txt <- function(model,
                                   model_id,
                                   out_dir = file.path("tables", "model_summaries")){
  make_dir(out_dir)
  out_file <- file.path(out_dir, paste0(model_id, "_summary.txt"))

  capture.output(summary(model), file = out_file)
  invisible(out_file)
}

save_model_diagnostics <- function(model,
                                   model_id,
                                   resp = NULL,
                                   ndraws = 1000){
  save_model_summary_txt(model, model_id)
  save_check_model_pdf(model, model_id)
  save_pp_check_pdf(model, model_id, resp = resp, ndraws = ndraws)
  invisible(model_id)
}
